Repository ironcore-dev/metalnet, pull requests merged in 2023-12, with the labels that each got.

#143 Add `CODEOWNERS` to project
  CODEOWNERS
Labels: size/XS, chore

#145 wrong name used: net-dpservice -> dpservice in docs
  README.md
  docs/development/setup.md
  docs/development/test.md
Labels: bug, documentation, size/XS

#146 Use ironcore's logo
  README.md
  docs/assets/logo.svg
Labels: bug, documentation, size/M
